module_name: "rvc"

# NOTE: Frequencies will be converted to an integer number of ms for a delay

buckets:
    high_frequency_ADCs:
        frequency_hz: 250
        parameters:
            currentSensorHigh_A:
                ADC: ADC1_IN3
                sensor: full_raw_voltage_sensor
                samples_buffered: 1
            brakeTempRearLeft_C: #Volt Sense 1
                ADC: ADC1_IN15
                sensor: full_raw_voltage_sensor
                samples_buffered: 1
            brakeTempRearRight_C: #Volt Sense 2
                ADC: ADC1_IN6
                sensor: full_raw_voltage_sensor
                samples_buffered: 1
            shockPosRearLeft_mm: #Volt Sense 3
                ADC: ADC1_IN0
                sensor: full_raw_voltage_sensor
                samples_buffered: 1
            shockPosRearRight_mm: #Volt Sense 4
                ADC: ADC1_IN5
                sensor: full_raw_voltage_sensor
                samples_buffered: 1
            brakePressureRear_psi:
                ADC: ADC1_IN4
                sensor: full_raw_voltage_sensor
                samples_buffered: 1
            currentSensorLow_A:
                ADC: ADC1_IN8
                sensor: full_raw_voltage_sensor
                samples_buffered: 1
            currentSensor_A:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            currentSensorStatus_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            # rearRideHeight_mm:
            #     ADC: ADC1_IN9
            #     sensor: full_raw_voltage_sensor # TODO make ride height sensor in gophersense
            #     samples_buffered: 1
            # radWaterTempIn_C:
            #     ADC: ADC1_IN11
            #     sensor: temp_sensor
            #     samples_buffered: 1
            # radWaterTempOut_C:
            #     ADC: ADC1_IN10
            #     sensor: temp_sensor
            #     samples_buffered: 1

    low_frequency:
        frequency_hz: 100
        parameters:
        # BSPD Faults
            bspdBrakePressureSensorFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            bspdTractiveSystemCurrentSensorFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            bspdTractiveSystemBrakingFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            bspdInputFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            bspdFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            
            coolantFanPower_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            coolantPumpPower_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            brakeBias_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1             
            brakeLightOn_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            vehicleBuzzerOn_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1