module_name: "rvc"

# NOTE: Frequencies will be converted to an integer number of ms for a delay

buckets:
    high_frequency_vcu:
        frequency_hz: 250
        parameters:
            currentSensorHigh_V:
                ADC: ADC1_IN3
                sensor: full_raw_voltage_sensor
                samples_buffered: 1
            brakeTempRearLeft_C:
                ADC: ADC1_IN15
                sensor: brake_temp_sensor
                samples_buffered: 1
            brakeTempRearRight_C:
                ADC: ADC1_IN6
                sensor: brake_temp_sensor
                samples_buffered: 1
            shockPosRearLeft_mm:
                ADC: ADC1_IN0
                sensor: linear_pos_sensor_50
                samples_buffered: 1
            shockPosRearRight_mm:
                ADC: ADC1_IN5
                sensor: linear_pos_sensor_50
                samples_buffered: 1
            brakePressureRear_psi:
                ADC: ADC1_IN4
                sensor: brake_pressure_sensor
                samples_buffered: 1
            currentSensorLow_V:
                ADC: ADC1_IN8
                sensor: full_raw_voltage_sensor
                samples_buffered: 1
            rearRideHeight_mm:
                ADC: ADC1_IN9
                sensor: full_raw_voltage_sensor # TODO make ride height sensor in gophersense
                samples_buffered: 1
            radWaterTempIn_C:
                ADC: ADC1_IN11
                sensor: temperature_sensor
                samples_buffered: 1
            radWaterTempOut_C:
                ADC: ADC1_IN10
                sensor: temperature_sensor
                samples_buffered: 1